

spring.datasource.username=root
spring.datasource.password=MYSQLPASSWD@1234!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/web

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.ssl.key-store=classpath:ssl.p12
server.ssl.key-store-password=SSLPASSWD@1234!
